### ISSUE TITLE
[Priority: Meidum] Clicking on buttons with slow Daemon response

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#207]
The daemon does not answer instantly every time by clicking on the Send button, and never on Create button. It should block the GUI and show some small animation until the daemon responds.  

![](https://media.giphy.com/media/jkSvCVEXWlOla/giphy.gif)

**Comment by nopara73** [comment]
This issue is being connected to more and more issue.  
My idea for expected behavior:  

When the user clicks on a button that executes ANY API command, the button should
1. Disable the all GUI elements (including the button being clicked on).
2. Add some spinning icon to the button: [!(http://www.itguyswa.com.au/wp-content/uploads/2016/10/spinning-loading-bar.gif)]  
2. When the API response arrives enable all GUI element and remove the spinning icon.

**Comment by nopara73** [comment]
# Implementation Example

I'll present an implementation example. Can you give a ConceptACK? @dangershony, @bokobza, @dev0tion and @bep42.  

## Illustration

![](https://i.imgur.com/M2X8sUg.gif)

## Code  

### 1. Go to JavaScript on button click:
`onclick="decryptWallet()"`
### 2. Disable pointer events
`document.getElementsByClassName("container").item(0).setAttribute("style", "pointer-events:none;");`
### 3. Add spinning glyphicon-cog
The spinning is implemented in CSS, I'll insert the code later.  
`glzphicon-cog` comes with Material Design Webfont (`mdi` npm package).  
`document.getElementById("decrypt-wallet-button").innerHTML = '<span class="glyphicon glyphicon-cog spinning"></span> Decrypting...';`
### 4. Make an async API request  
### 5. When response arrived:  
### 6. Change back the button to original
`document.getElementById("decrypt-wallet-button").innerHTML = "Decrypt";`
### 7. Enable pointer events
`document.getElementsByClassName("container").item(0).setAttribute("style", "pointer-events:all;");`

## Spinning CSS
```css
.glyphicon.spinning {
    animation: spin 1s infinite linear;
    -webkit-animation: spin2 1s infinite linear;
}

@keyframes spin {
    from {
        transform: scale(1) rotate(0deg);
    }

    to {
        transform: scale(1) rotate(360deg);
    }
}

@-webkit-keyframes spin2 {
    from {
        -webkit-transform: rotate(0deg);
    }

    to {
        -webkit-transform: rotate(360deg);
    }
}
```
